version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - db-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: asdf

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: asdf
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123

  # redis1:
  #   container_name: redis1
  #   image: redis
  #   command: redis-server --requirepass asdf
  #   ports:
  #   - '6379:6379'

  app:
    image: 495687440051.dkr.ecr.ap-northeast-1.amazonaws.com/mongo-express:latest
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 8080:8080
    working_dir: /app
    depends_on:
      - mongodb
    environment:
      - VIRTUAL_HOST=dev.silver-tercel.com
      - LETSENCRYPT_HOST=dev.silver-tercel.com
      - LETSENCRYPT_EMAIL=steedude@gmail.com
      - VIRTUAL_PORT=8080

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=steedude@gmail.com
      # - NGINX_PROXY_CONTAINER=nginx-proxy

volumes:
  db-data:
  vhost:
  html:
  certs:
  acme:
